[config]
skip_core_tasks = true


[tasks.build]
script = [
    "env CARGO_Z_BUILD_STD=core,alloc cargo build --target x86_64-unknown-uefi",
]

[tasks.test]
script = [
    "cargo test"
]

[tasks.iso]
script = [
    "cargo make build",
    "sh ./scripts/build_iso.sh ${@}"
]

[tasks.iso.windows]
script = [
    "cargo make build",
    "call .\\scripts\\build_iso.bat ${@}"
]
# ---
# ---
[tasks.init_project]
script = [
    "bash ./init.sh"
]

[tasks.init_project.windows]
script = [
    "call .\\init.bat"
]
# ---
[tasks.update_microcode]
script = [
    "bash ./scripts/get_microcode.sh"
]

[tasks.update_microcode.windows]
script = [
    "call .\\scripts\\get_microcode.bat"
]
# ---


[tasks.run]
script_runner = "${TARGET_SHELL}"
command = "cargo"
args = ["run", "--features", "features_enable_debug_mode", "--target", "x86_64-unknown-uefi", "${@}"]
