[resolver]
version = "2"

[build]
target = "x86_64-unknown-uefi"
rustc-wrapper = "/usr/bin/sccache"

[target.x86_64-unknown-uefi]
rustflags = [
    "-Z", "cf-protection=full",
    "-C", "relocation-model=pic",
    "-C", "target-cpu=x86-64-v2",
    "-C", "no-redzone=y",
    "-C", "panic=abort",
]

runner = "sh ./scripts/run.sh"

[unstable]
build-std = ["core", "alloc"]